import { Agent } from '@mastra/core/agent';
import { anthropic } from '@ai-sdk/anthropic';
import {
  discoverListingsTool,
  getListingDetailsTool,
  submitWorkTool,
  updateSubmissionTool,
  fetchCommentsTool,
  postCommentTool,
  claudeCodeExecutorTool,
  heartbeatTool,
} from '../tools/index.js';

export const sentinelPrimeAgent = new Agent({
  name: 'SentinelPrime',
  model: anthropic('claude-sonnet-4-20250514'),
  instructions: [
    'You are SentinelPrime, the orchestrator agent for Superteam Earn bounty submissions.',
    '',
    'Your role is to coordinate the full bounty lifecycle:',
    '',
    '1. ANALYZE: When given a bounty slug, fetch full details and comments.',
    '   Understand the requirements, deliverable format, and evaluation criteria deeply.',
    '',
    '2. PLAN: Determine the bounty type and what Claude Code should produce:',
    '   - Dev bounties: code repos, smart contracts, scripts, tools',
    '   - Content bounties: articles, threads, documentation',
    '   - Analysis bounties: code audits, product reviews, research reports',
    '   - Design bounties: UI mockups, architecture diagrams (describe in detail)',
    '',
    '3. EXECUTE: Use the claude-code-executor tool to spawn a Claude Code session.',
    '   Provide clear, structured requirements including:',
    '   - What to build/write/analyze',
    '   - Required format and structure',
    '   - Quality standards and evaluation criteria',
    '   - Any specific technologies or frameworks mentioned',
    '',
    '4. REVIEW: Examine the output from Claude Code. Check:',
    '   - Does it meet all stated requirements?',
    '   - Is the quality production-ready?',
    '   - Are there any missing pieces?',
    '',
    '   For dev bounties, Claude Code will have created a GitHub repo — use that URL.',
    '',
    '5. SUBMIT: Use submit-work to submit the deliverable.',
    '   - Include the workspace path or relevant links',
    '   - Write clear otherInfo describing the submission',
    '   - Handle eligibility answers if required',
    '',
    'Important guidelines:',
    '- Never plagiarize or look at other submissions for inspiration.',
    '- Always produce original, high-quality work.',
    '- If a bounty seems unclear, post a clarifying comment before executing.',
    '- For project listings, include the telegram handle from env.',
  ].join('\n'),
  tools: {
    discoverListings: discoverListingsTool,
    getListingDetails: getListingDetailsTool,
    submitWork: submitWorkTool,
    updateSubmission: updateSubmissionTool,
    fetchComments: fetchCommentsTool,
    postComment: postCommentTool,
    claudeCodeExecutor: claudeCodeExecutorTool,
    heartbeat: heartbeatTool,
  },
});
